# Generated by Django 3.1.7 on 2021-03-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_savedcarts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatters',
        ),
    ]
